"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
const form_vue_vue_type_script_setup_true_lang = require("./form.vue.js");
const formItem_vue_vue_type_script_setup_true_lang = require("./form-item.vue.js");
const install = require("../utils/install.js");
const Form = install.withInstall(form_vue_vue_type_script_setup_true_lang.default, "AForm");
const FormItem = install.withInstall(formItem_vue_vue_type_script_setup_true_lang.default, "AFormItem");
exports.AFormItem = FormItem;
exports.FormItem = FormItem;
exports.default = Form;
