import type { Plugin } from 'vue';
import Alert from './alert';
import Badge from './badge';
import Breadcrumb from './breadcrumb';
import Button from './button';
import ConfigProvider from './config-provider';
import Divider from './divider';
import Empty from './empty';
import Flex from './flex';
import Icon from './icon';
import Space from './space';
import Spin from './spin';
import Steps from './steps';
import Tag from './tag';
import Tabs from './tabs';
import Typography, { Link, Paragraph, Text, Title } from './typography';
declare const AheartUI: Plugin;
export { Button, ConfigProvider, Space, Divider, Flex, Icon, Typography, Title, Text, Paragraph, Link, Tag, Badge, Alert, Spin, Empty, Breadcrumb, Tabs, Steps };
export default AheartUI;
