import { test, expect } from '@playwright/test'

test('D4 Tree linked checks expose mixed state and lazy failure retry', async ({ page }) => {
  await page.goto('/components/tree')
  await page.waitForFunction(() => Boolean((document.querySelector('#app') as any)?.__vue_app__))
  const linked = page.getByRole('region', { name: 'D4 树联动示例' })
  const parent = linked.getByRole('treeitem', { name: '研发组', exact: true })
  await expect(parent).toHaveAttribute('aria-checked', 'mixed')
  await parent.getByRole('checkbox', { name: 'Select 研发组', exact: true }).check()
  await expect(parent).toHaveAttribute('aria-checked', 'true')
  await expect(linked.getByRole('status')).toContainText('group,frontend,backend')
  await expect(linked.getByRole('checkbox', { name: 'Select 受限节点' })).not.toBeChecked()
  await linked.getByRole('checkbox', { name: 'Select 后端' }).uncheck()
  await expect(parent).toHaveAttribute('aria-checked', 'mixed')
  const lazy = page.getByRole('region', { name: 'D4 树加载示例' })
  await lazy.getByRole('button', { name: 'Expand node' }).click()
  await expect(lazy.getByRole('button', { name: '重试加载 按需加载组' })).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('lazy-error.png') })
  await lazy.getByRole('button', { name: '重试加载 按需加载组' }).press('Enter')
  await expect(lazy.getByRole('treeitem', { name: '按需加载组', exact: true })).toBeFocused()
  await expect(lazy.getByRole('treeitem', { name: '已加载节点' })).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('lazy-loaded.png') })
})

test('D4 TreeSelect searching retains the full linked selection model', async ({ page }) => {
  await page.goto('/components/tree-select')
  await page.waitForFunction(() => Boolean((document.querySelector('#app') as any)?.__vue_app__))
  const region = page.getByRole('region', { name: 'D4 树选择勾选示例' })
  await region.getByRole('combobox').click()
  const panel = page.getByRole('dialog', { name: '树选择' })
  await panel.getByRole('searchbox').fill('概览')
  await panel.getByRole('checkbox', { name: 'Select 工作台', exact: true }).check()
  await expect(region.getByRole('status')).toContainText('workspace,overview,settings')
  await expect(panel).toBeVisible()
  await panel.getByRole('searchbox').fill('')
  await expect(panel.getByRole('checkbox', { name: 'Select 工作台', exact: true })).toBeChecked()
  await page.screenshot({ path: test.info().outputPath('tree-select-checked.png') })
})
