import { expect, test, type Page } from '@playwright/test'

function runtimeErrors(page: Page) {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  return errors
}

test('local current-page selection excludes disabled rows, preserves typed keys and rejects parent updates', async ({ page }) => {
  const errors = runtimeErrors(page)
  await page.goto('/components/table')
  const demo = page.getByRole('region', { name: 'D5 本地客户选择' })
  const all = demo.getByRole('checkbox', { name: 'Select all rows on current page' })
  await expect(demo.locator('tbody tr')).toHaveCount(3)
  await expect(demo.getByRole('checkbox', { name: 'Select row 2', exact: true })).toBeDisabled()
  await all.click()
  await expect(demo.getByRole('status')).toContainText('number:1、string:1')
  await expect(demo.locator('tbody input:checked')).toHaveCount(2)
  await demo.locator('.aheart-pagination__next').click()
  await expect(demo.locator('tbody')).toContainText('第二页客户甲')
  await expect(all).not.toBeChecked()
  await all.click()
  await expect(demo.getByRole('status')).toContainText('number:1、string:1、number:3、number:4、number:5')
  await demo.getByRole('button', { name: '拒绝选择更新' }).click()
  await all.click()
  await expect(all).toBeChecked()
  await expect(demo.locator('tbody input:checked')).toHaveCount(3)
  await expect(demo.getByRole('status')).toContainText('选择请求：3')
  expect(errors).toEqual([])
})

test('native radio groups restore the accepted row after a rejected selection request', async ({ page }) => {
  const errors = runtimeErrors(page)
  await page.goto('/components/table')
  const demo = page.getByRole('region', { name: 'D5 受控单选' })
  const radios = demo.getByRole('radio')
  await expect(radios.first()).toBeChecked()
  await radios.nth(1).click()
  await expect(radios.first()).toBeChecked()
  await expect(radios.nth(1)).not.toBeChecked()
  await expect(demo.getByRole('status')).toContainText('单选请求：1')
  expect(errors).toEqual([])
})

test('server query controls wait for acceptance without reordering filtering or slicing the response', async ({ page }) => {
  const errors = runtimeErrors(page)
  await page.goto('/components/table')
  const demo = page.getByRole('region', { name: 'D5 服务端请求' })
  const active = demo.locator('[aria-current="page"]')
  await expect(active).toHaveText('2')
  await demo.getByRole('button', { name: 'Sort 服务端评分', exact: true }).click()
  await expect(demo.getByRole('status')).toContainText('待接受：sort，页码1')
  await expect(active).toHaveText('2')
  await expect(demo.locator('th[aria-sort]')).toHaveAttribute('aria-sort', 'none')
  await demo.getByRole('button', { name: '接受服务端请求' }).click()
  await expect(active).toHaveText('1')
  await expect(demo.locator('th[aria-sort]')).toHaveAttribute('aria-sort', 'ascending')
  await expect(demo.locator('tbody tr').first()).toContainText('服务器先返回高分')
  await demo.getByRole('button', { name: '只看高分', exact: true }).click()
  await expect(demo.getByRole('button', { name: '只看高分', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await demo.getByRole('button', { name: '接受服务端请求' }).click()
  await expect(demo.getByRole('button', { name: '只看高分', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(demo.locator('tbody tr')).toHaveCount(2)
  await demo.locator('.aheart-pagination__next').click()
  await expect(active).toHaveText('1')
  await demo.getByRole('button', { name: '接受服务端请求' }).click()
  await expect(active).toHaveText('2')
  await expect(demo.locator('tbody tr')).toHaveCount(2)
  expect(errors).toEqual([])
})

test('Table page-size rejection restores the native select and accepted requests update both dimensions once', async ({ page }) => {
  const errors = runtimeErrors(page)
  await page.goto('/components/table')
  const demo = page.getByRole('region', { name: 'D5 受控分页' })
  await demo.getByRole('combobox').selectOption('20')
  await expect(demo.getByRole('combobox')).toHaveValue('10')
  await expect(demo.locator('[aria-current="page"]')).toHaveText('5')
  await expect(demo.getByRole('status')).toContainText('分页请求：1')
  await demo.getByRole('button', { name: '接受分页更新' }).click()
  await demo.getByRole('combobox').selectOption('50')
  await expect(demo.getByRole('combobox')).toHaveValue('50')
  await expect(demo.locator('[aria-current="page"]')).toHaveText('2')
  await expect(demo.getByRole('status')).toContainText('分页请求：2')
  await demo.getByRole('spinbutton').fill('1')
  await demo.getByRole('spinbutton').press('Enter')
  await expect(demo.locator('[aria-current="page"]')).toHaveText('1')
  await expect(demo.getByRole('status')).toContainText('分页请求：3')
  expect(errors).toEqual([])
})

test('standalone Pagination rejects keyboard and size requests and disables every control', async ({ page }) => {
  const errors = runtimeErrors(page)
  await page.goto('/components/pagination')
  const demo = page.getByRole('region', { name: 'D5 独立分页' })
  await demo.getByRole('combobox').selectOption('50')
  await expect(demo.getByRole('combobox')).toHaveValue('10')
  await demo.locator('.aheart-pagination__next').focus()
  await page.keyboard.press('Enter')
  await demo.getByRole('spinbutton').fill('2')
  await demo.getByRole('spinbutton').press('Enter')
  await expect(demo.locator('[aria-current="page"]')).toHaveText('5')
  await expect(demo.getByRole('status')).toContainText('请求3次')
  await demo.getByRole('button', { name: '禁用分页' }).click()
  const pagination = demo.locator('.aheart-pagination')
  for (const control of await pagination.locator('button, select, input').all()) await expect(control).toBeDisabled()
  expect(errors).toEqual([])
})
