import { expect, test } from '@playwright/test'

test('account form validates dependencies and recovers from server field errors', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/components/form')
  const form = page.getByRole('region', { name: '账户资料表单' })
  const email = form.getByRole('textbox', { name: '账户邮箱' })
  const password = form.locator('[data-name="password"] input')
  const confirmation = form.locator('[data-name="confirm"] input')
  await expect(password).toHaveAccessibleName(/^密码\s*:?\s*$/)
  await expect(confirmation).toHaveAccessibleName(/^确认密码\s*:?\s*$/)
  await email.fill('taken@example.com')
  await password.fill('secret1')
  await confirmation.fill('different')
  await confirmation.press('Tab')
  await expect(confirmation).toHaveAttribute('aria-invalid', 'true')
  await expect(form.getByRole('alert')).toContainText('两次密码不一致')

  await password.fill('different')
  await expect(confirmation).not.toHaveAttribute('aria-invalid', 'true')
  await form.getByRole('button', { name: '保存资料', exact: true }).click()
  await expect(email).toHaveAttribute('aria-invalid', 'true')
  await expect(form.getByRole('alert')).toContainText('该邮箱已注册')
  await form.evaluate((element) => window.scrollTo(0, window.scrollY + element.getBoundingClientRect().top - 128))
  await form.screenshot({ path: testInfo.outputPath('server-error.png'), animations: 'disabled' })
  await email.fill('free@example.com')
  await form.getByRole('button', { name: '保存资料', exact: true }).click()
  await expect(form.getByRole('status')).toHaveText('账户资料已保存')
  await expect(email).not.toHaveAttribute('aria-invalid', 'true')
  await expect(email.locator('..')).not.toHaveClass(/aheart-input--error/)
  await form.evaluate((element) => window.scrollTo(0, window.scrollY + element.getBoundingClientRect().top - 128))
  await form.screenshot({ path: testInfo.outputPath('saved.png'), animations: 'disabled' })

  const city = form.getByRole('textbox', { name: '收货城市' })
  await city.fill('杭州')
  await form.getByRole('button', { name: '移除收货地址' }).click()
  await expect(city).toHaveCount(0)
  await form.getByRole('button', { name: '添加收货地址' }).click()
  await expect(city).toHaveValue('')
  expect(errors).toEqual([])
})
