"use strict";
Object.defineProperties(exports, { __esModule: { value: true }, [Symbol.toStringTag]: { value: "Module" } });
const timePicker_vue_vue_type_script_setup_true_lang = require("./time-picker.vue.js");
const timeRangePicker_vue_vue_type_script_setup_true_lang = require("./time-range-picker.vue.js");
const install = require("../utils/install.js");
const TimeRangePicker = install.withInstall(timeRangePicker_vue_vue_type_script_setup_true_lang.default, "ATimeRangePicker");
const InstalledTimePicker = install.withInstall(timePicker_vue_vue_type_script_setup_true_lang.default, "ATimePicker");
InstalledTimePicker.RangePicker = TimeRangePicker;
const TimePicker = InstalledTimePicker;
exports.TimeRangePicker = TimeRangePicker;
exports.default = TimePicker;
