import type { Plugin } from 'vue';
import Button from './button';
import ConfigProvider from './config-provider';
import Divider from './divider';
import Flex from './flex';
import Icon from './icon';
import Space from './space';
import Typography, { Link, Paragraph, Text, Title } from './typography';
declare const AheartUI: Plugin;
export { Button, ConfigProvider, Space, Divider, Flex, Icon, Typography, Title, Text, Paragraph, Link };
export default AheartUI;
