import type { Plugin } from 'vue';
import Alert from './alert';
import Badge from './badge';
import Breadcrumb from './breadcrumb';
import Button from './button';
import Card from './card';
import Checkbox from './checkbox';
import ConfigProvider from './config-provider';
import Descriptions from './descriptions';
import Divider from './divider';
import Dropdown from './dropdown';
import Empty from './empty';
import Flex from './flex';
import Form, { FormItem } from './form';
import Icon from './icon';
import Input from './input';
import InputNumber from './input-number';
import Menu from './menu';
import Pagination from './pagination';
import Radio from './radio';
import Select from './select';
import Space from './space';
import Spin from './spin';
import Steps from './steps';
import Switch from './switch';
import Table from './table';
import Tag from './tag';
import Tabs from './tabs';
import Textarea from './textarea';
import Typography, { Link, Paragraph, Text, Title } from './typography';
declare const AheartUI: Plugin;
export { Button, ConfigProvider, Space, Divider, Flex, Icon, Typography, Title, Text, Paragraph, Link, Tag, Badge, Alert, Spin, Empty, Breadcrumb, Dropdown, Menu, Tabs, Steps, Input, Textarea, InputNumber, Checkbox, Radio, Switch, Card, Descriptions, Pagination, Select, Form, FormItem, Table };
export default AheartUI;
