"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const floatingCore = require("./floating-core.js");
const useFloatingPosition = require("./use-floating-position.js");
exports.floatingPlacements = floatingCore.floatingPlacements;
exports.floatingTriggers = floatingCore.floatingTriggers;
exports.getFloatingPopupStyle = floatingCore.getFloatingPopupStyle;
exports.isFloatingPlacement = floatingCore.isFloatingPlacement;
exports.isFloatingTrigger = floatingCore.isFloatingTrigger;
exports.isFloatingTriggerProp = floatingCore.isFloatingTriggerProp;
exports.normalizeFloatingTriggers = floatingCore.normalizeFloatingTriggers;
exports.fromFloatingUIPlacement = useFloatingPosition.fromFloatingUIPlacement;
exports.getFloatingArrowStaticSide = useFloatingPosition.getFloatingArrowStaticSide;
exports.toFloatingUIPlacement = useFloatingPosition.toFloatingUIPlacement;
exports.useFloatingPosition = useFloatingPosition.useFloatingPosition;
